# Generated by Django 6.0.5 on 2026-05-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('url_demo', models.URLField(blank=True)),
                ('url_github', models.URLField(blank=True)),
                ('tecnologias', models.CharField(help_text='Separadas por comas', max_length=300)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
