# Generated by Django 6.0.5 on 2026-05-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(help_text='Tecnologías separadas por comas. Ej: Python, Django, HTML', max_length=300),
        ),
    ]
