# Generated by Django 6.0.5 on 2026-05-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(help_text='Breve descripción del artículo', max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
